### ISSUE TITLE
Archive folder is fulling my disk

### ISSUE THREAD

**Issue by pascalandy** [nimmis/docker-resilio-sync#1]
Hi,
Using your project since a month and it's all stable here :) Wondering if we could modify the config so Resilio keep older files in `.sync/Archive` for only **X days**.

It looks that at the moment, it keeps older files (and DIR) for 30 days which is overkill! In one one week, my disk has been full by 32G of garbage. 

Thank you !!

**Comment by pascalandy** [comment]
I created a cron to take care of this on all my nodes.

**Comment by nimmis** [comment]
I have fixed it with the Resilio configuration, please look at the variables RSLSYNC_TRASH, RSLSYNC_TRASH_TIME and RSLSYNC_SIZE in the README.md file for the new configuration alternatives.

**Comment by pascalandy** [comment]
Thank you sooo much!! This is awesome
