### ISSUE TITLE
Please add the ability to change the listen port

### ISSUE THREAD

**Issue by reedog117** [nimmis/docker-resilio-sync#5]
I have a workflow where I am running multiple copies of this on the same docker host but sync'ing different folders. Please allow the ability to change the listening port via an environment variable - in the meantime it still syncs but has to open an outgoing connection vs accepting an inbound one.

**Comment by pascalandy** [comment]
Your question is related to the way you have to deploy an app with docker. It's not related to this app. I guess you are looking to do something like:

```

# NODE 1
docker service create \
  --name resilio1 --hostname resilio1 \
  --network ${NTW_RESILIO} --replicas "1" \
  --constraint 'node.labels.nodeid == 1' \
  --publish "33331:33333" \
  -e RSLSYNC_SECRET=$(cat ${secret_token_path}) \
  --mount type=bind,source=${my_path},target=/data \
  devmtl/resilio:2.6.3

# NODE 2
docker service create \
  --name resilio2 --hostname resilio2 \
  --network ${NTW_RESILIO} --replicas "1" \
  --constraint 'node.labels.nodeid == 2' \
  --publish "33332:33333" \
  -e RSLSYNC_SECRET=$(cat ${secret_token_path}) \
  --mount type=bind,source=${my_path},target=/data \
  devmtl/resilio:2.6.3
```

**Comment by nimmis** [comment]
resolved by @pascalandy
